"""Embed fonts and images into trailer/src.html and write muneeb-trailer.html.

Run from the repo root: python3 trailer/build.py
"""
import base64
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
ASSETS = ROOT / "assets"
OUT = ROOT.parent / "muneeb-trailer.html"

FONTS = [
    ("Almarai", 400, "normal", "almarai-latin-400-normal.woff2"),
    ("Almarai", 800, "normal", "almarai-latin-800-normal.woff2"),
    ("Instrument Serif", 400, "italic", "instrument-serif-latin-400-italic.woff2"),
]


def data_uri(path, mime):
    return f"data:{mime};base64," + base64.b64encode(path.read_bytes()).decode()


fonts = [
    {"family": fam, "weight": w, "style": st, "src": data_uri(ASSETS / "fonts" / f, "font/woff2")}
    for fam, w, st, f in FONTS
]
images = {p.stem: data_uri(p, "image/jpeg") for p in sorted((ASSETS / "img").glob("*.jpg"))}

block = (
    "/* Embedded assets, generated by trailer/build.py */\n"
    f"const FONTS = {json.dumps(fonts)};\n"
    f"const IMAGES = {json.dumps(images, indent=0)};"
)
src = (ROOT / "src.html").read_text()
assert "/*__ASSETS__*/" in src
OUT.write_text(src.replace("/*__ASSETS__*/", block))
print(f"wrote {OUT} ({OUT.stat().st_size / 1e6:.2f} MB, {len(images)} images, {len(fonts)} fonts)")
